#ifndef MAIN_H
#define MAIN_H
#define COACH_VERSION_MAJOR 0
#define COACH_VERSION_MINOR 1
#define COACH_VERSION_PATCH 0

#define XSTR(S) STR(S)
#define STR(S) #S

#ifndef COACH_VERSION
#if COACH_VERSION_PATCH > 0
#define COACH_VERSION "v"XSTR(COACH_VERSION_MAJOR)"."XSTR(COACH_VERSION_MINOR)"."XSTR(COACH_VERSION_PATCH)"-zip"
#else
#define COACH_VERSION "v"XSTR(COACH_VERSION_MAJOR)"."XSTR(COACH_VERSION_MINOR)"-zip"

#endif //COACH_VERSION_PATCH > 0
#endif //COACH_VERSION
#endif //MAIN_H
